import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Cookie, Settings2, ShieldCheck, X } from 'lucide-react';

const KEY = 'kivu_cookie_consent';
const CookieConsent = () => {
  const [open, setOpen] = useState(false);
  const [settings, setSettings] = useState(false);
  const [choices, setChoices] = useState({ functional: false, analytics: false });
  useEffect(() => {
    try { if (!localStorage.getItem(KEY)) setOpen(true); } catch { setOpen(true); }
    const openSettings = () => { setSettings(true); setOpen(true); };
    window.addEventListener('open-cookie-settings', openSettings);
    return () => window.removeEventListener('open-cookie-settings', openSettings);
  }, []);
  const save = (value) => { try { localStorage.setItem(KEY, JSON.stringify(value)); } catch {} setOpen(false); setSettings(false); };
  return <AnimatePresence>{open && <motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 28 }} className="fixed inset-x-0 bottom-0 z-[2900] p-3 sm:p-5"><div className="mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-700 dark:bg-[#0B101D] sm:p-6"><div className="flex gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-blue-600/10 text-blue-600"><Cookie size={22} /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-slate-900 dark:text-white">Votre confidentialité compte</h2><p className="mt-1 text-sm leading-relaxed text-slate-500 dark:text-slate-400">Nous utilisons les cookies essentiels au fonctionnement du site. Vous pouvez accepter les préférences optionnelles ou les personnaliser.</p></div><button onClick={() => save({ essential: true, functional: false, analytics: false, choice: 'essential' })} className="text-slate-400 hover:text-slate-700 dark:hover:text-white"><X size={18} /></button></div>{settings && <div className="mt-4 space-y-3 rounded-2xl bg-slate-50 p-4 dark:bg-white/[0.04]"><label className="flex items-center justify-between gap-3 text-sm font-semibold text-slate-700 dark:text-slate-200"><span><ShieldCheck size={15} className="mr-2 inline text-emerald-500" />Essentiels <small className="font-normal text-slate-500">(toujours actifs)</small></span><input checked disabled type="checkbox" /></label><label className="flex items-center justify-between gap-3 text-sm font-semibold text-slate-700 dark:text-slate-200"><span>Préférences fonctionnelles</span><input checked={choices.functional} onChange={(e) => setChoices({ ...choices, functional: e.target.checked })} type="checkbox" /></label><label className="flex items-center justify-between gap-3 text-sm font-semibold text-slate-700 dark:text-slate-200"><span>Mesure d’audience</span><input checked={choices.analytics} onChange={(e) => setChoices({ ...choices, analytics: e.target.checked })} type="checkbox" /></label></div>}<div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button onClick={() => setSettings(!settings)} className="rounded-xl px-4 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/5"><Settings2 size={15} className="mr-1.5 inline" />Personnaliser</button><button onClick={() => save({ essential: true, ...choices, choice: 'custom' })} className={`${settings ? '' : 'hidden'} rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white dark:bg-white dark:text-slate-900`}>Enregistrer mes choix</button><button onClick={() => save({ essential: true, functional: true, analytics: true, choice: 'all' })} className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white hover:bg-blue-700">Tout accepter</button></div></div></div></div></motion.div>}</AnimatePresence>;
};
export default CookieConsent;
